# Generated by Django 5.0.6 on 2024-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_userdetails',
            name='bio',
            field=models.CharField(default='Помогите :D', max_length=500),
        ),
    ]
